In [1]:
#导入相关包
import numpy as np
import matplotlib.pyplot as plt
import random
import netCDF4
import datetime
import seaborn as sns
from global_land_mask import globe
from scipy import interpolate
from sklearn.metrics import silhouette_samples
from sklearn.preprocessing import StandardScaler
#plt.rcParams['font.sans-serif'] = ['SimHei'] #中文支持
#%matplotlib inline

In [2]:
data_rmm=np.loadtxt('/WdHeDisk/users/zhangnong/MJO/711_test/pca_RMM_1950_2022.txt')
print(data_rmm.shape)

(26209, 3)


In [5]:
j=0
for i in range(0,26145,3):
    print(j)
    print(data_rmm[i,0])
    j=j+1

0
19500501.0
1
19500504.0
2
19500507.0
3
19500510.0
4
19500513.0
5
19500516.0
6
19500519.0
7
19500522.0
8
19500525.0
9
19500528.0
10
19500531.0
11
19500603.0
12
19500606.0
13
19500609.0
14
19500612.0
15
19500615.0
16
19500618.0
17
19500621.0
18
19500624.0
19
19500627.0
20
19500630.0
21
19500703.0
22
19500706.0
23
19500709.0
24
19500712.0
25
19500715.0
26
19500718.0
27
19500721.0
28
19500724.0
29
19500727.0
30
19500730.0
31
19500802.0
32
19500805.0
33
19500808.0
34
19500811.0
35
19500814.0
36
19500817.0
37
19500820.0
38
19500823.0
39
19500826.0
40
19500829.0
41
19500901.0
42
19500904.0
43
19500907.0
44
19500910.0
45
19500913.0
46
19500916.0
47
19500919.0
48
19500922.0
49
19500925.0
50
19500928.0
51
19501001.0
52
19501004.0
53
19501007.0
54
19501010.0
55
19501013.0
56
19501016.0
57
19501019.0
58
19501022.0
59
19501025.0
60
19501028.0
61
19501031.0
62
19501103.0
63
19501106.0
64
19501109.0
65
19501112.0
66
19501115.0
67
19501118.0
68
19501121.0
69
19501124.0
70
19501127.0
71
19501130.0
72

19590701.0
1117
19590704.0
1118
19590707.0
1119
19590710.0
1120
19590713.0
1121
19590716.0
1122
19590719.0
1123
19590722.0
1124
19590725.0
1125
19590728.0
1126
19590731.0
1127
19590803.0
1128
19590806.0
1129
19590809.0
1130
19590812.0
1131
19590815.0
1132
19590818.0
1133
19590821.0
1134
19590824.0
1135
19590827.0
1136
19590830.0
1137
19590902.0
1138
19590905.0
1139
19590908.0
1140
19590911.0
1141
19590914.0
1142
19590917.0
1143
19590920.0
1144
19590923.0
1145
19590926.0
1146
19590929.0
1147
19591002.0
1148
19591005.0
1149
19591008.0
1150
19591011.0
1151
19591014.0
1152
19591017.0
1153
19591020.0
1154
19591023.0
1155
19591026.0
1156
19591029.0
1157
19591101.0
1158
19591104.0
1159
19591107.0
1160
19591110.0
1161
19591113.0
1162
19591116.0
1163
19591119.0
1164
19591122.0
1165
19591125.0
1166
19591128.0
1167
19591201.0
1168
19591204.0
1169
19591207.0
1170
19591210.0
1171
19591213.0
1172
19591216.0
1173
19591219.0
1174
19591222.0
1175
19591225.0
1176
19591228.0
1177
19591231.0
1178
19600103

2439
19700513.0
2440
19700516.0
2441
19700519.0
2442
19700522.0
2443
19700525.0
2444
19700528.0
2445
19700531.0
2446
19700603.0
2447
19700606.0
2448
19700609.0
2449
19700612.0
2450
19700615.0
2451
19700618.0
2452
19700621.0
2453
19700624.0
2454
19700627.0
2455
19700630.0
2456
19700703.0
2457
19700706.0
2458
19700709.0
2459
19700712.0
2460
19700715.0
2461
19700718.0
2462
19700721.0
2463
19700724.0
2464
19700727.0
2465
19700730.0
2466
19700802.0
2467
19700805.0
2468
19700808.0
2469
19700811.0
2470
19700814.0
2471
19700817.0
2472
19700820.0
2473
19700823.0
2474
19700826.0
2475
19700829.0
2476
19700901.0
2477
19700904.0
2478
19700907.0
2479
19700910.0
2480
19700913.0
2481
19700916.0
2482
19700919.0
2483
19700922.0
2484
19700925.0
2485
19700928.0
2486
19701001.0
2487
19701004.0
2488
19701007.0
2489
19701010.0
2490
19701013.0
2491
19701016.0
2492
19701019.0
2493
19701022.0
2494
19701025.0
2495
19701028.0
2496
19701031.0
2497
19701103.0
2498
19701106.0
2499
19701109.0
2500
19701112.0
2501
197

3891
19820416.0
3892
19820419.0
3893
19820422.0
3894
19820425.0
3895
19820428.0
3896
19820501.0
3897
19820504.0
3898
19820507.0
3899
19820510.0
3900
19820513.0
3901
19820516.0
3902
19820519.0
3903
19820522.0
3904
19820525.0
3905
19820528.0
3906
19820531.0
3907
19820603.0
3908
19820606.0
3909
19820609.0
3910
19820612.0
3911
19820615.0
3912
19820618.0
3913
19820621.0
3914
19820624.0
3915
19820627.0
3916
19820630.0
3917
19820703.0
3918
19820706.0
3919
19820709.0
3920
19820712.0
3921
19820715.0
3922
19820718.0
3923
19820721.0
3924
19820724.0
3925
19820727.0
3926
19820730.0
3927
19820802.0
3928
19820805.0
3929
19820808.0
3930
19820811.0
3931
19820814.0
3932
19820817.0
3933
19820820.0
3934
19820823.0
3935
19820826.0
3936
19820829.0
3937
19820901.0
3938
19820904.0
3939
19820907.0
3940
19820910.0
3941
19820913.0
3942
19820916.0
3943
19820919.0
3944
19820922.0
3945
19820925.0
3946
19820928.0
3947
19821001.0
3948
19821004.0
3949
19821007.0
3950
19821010.0
3951
19821013.0
3952
19821016.0
3953
198

5224
19930328.0
5225
19930331.0
5226
19930403.0
5227
19930406.0
5228
19930409.0
5229
19930412.0
5230
19930415.0
5231
19930418.0
5232
19930421.0
5233
19930424.0
5234
19930427.0
5235
19930430.0
5236
19930503.0
5237
19930506.0
5238
19930509.0
5239
19930512.0
5240
19930515.0
5241
19930518.0
5242
19930521.0
5243
19930524.0
5244
19930527.0
5245
19930530.0
5246
19930602.0
5247
19930605.0
5248
19930608.0
5249
19930611.0
5250
19930614.0
5251
19930617.0
5252
19930620.0
5253
19930623.0
5254
19930626.0
5255
19930629.0
5256
19930702.0
5257
19930705.0
5258
19930708.0
5259
19930711.0
5260
19930714.0
5261
19930717.0
5262
19930720.0
5263
19930723.0
5264
19930726.0
5265
19930729.0
5266
19930801.0
5267
19930804.0
5268
19930807.0
5269
19930810.0
5270
19930813.0
5271
19930816.0
5272
19930819.0
5273
19930822.0
5274
19930825.0
5275
19930828.0
5276
19930831.0
5277
19930903.0
5278
19930906.0
5279
19930909.0
5280
19930912.0
5281
19930915.0
5282
19930918.0
5283
19930921.0
5284
19930924.0
5285
19930927.0
5286
199

6539
20040115.0
6540
20040118.0
6541
20040121.0
6542
20040124.0
6543
20040127.0
6544
20040130.0
6545
20040202.0
6546
20040205.0
6547
20040208.0
6548
20040211.0
6549
20040214.0
6550
20040217.0
6551
20040220.0
6552
20040223.0
6553
20040226.0
6554
20040229.0
6555
20040303.0
6556
20040306.0
6557
20040309.0
6558
20040312.0
6559
20040315.0
6560
20040318.0
6561
20040321.0
6562
20040324.0
6563
20040327.0
6564
20040330.0
6565
20040402.0
6566
20040405.0
6567
20040408.0
6568
20040411.0
6569
20040414.0
6570
20040417.0
6571
20040420.0
6572
20040423.0
6573
20040426.0
6574
20040429.0
6575
20040502.0
6576
20040505.0
6577
20040508.0
6578
20040511.0
6579
20040514.0
6580
20040517.0
6581
20040520.0
6582
20040523.0
6583
20040526.0
6584
20040529.0
6585
20040601.0
6586
20040604.0
6587
20040607.0
6588
20040610.0
6589
20040613.0
6590
20040616.0
6591
20040619.0
6592
20040622.0
6593
20040625.0
6594
20040628.0
6595
20040701.0
6596
20040704.0
6597
20040707.0
6598
20040710.0
6599
20040713.0
6600
20040716.0
6601
200

7970
20151017.0
7971
20151020.0
7972
20151023.0
7973
20151026.0
7974
20151029.0
7975
20151101.0
7976
20151104.0
7977
20151107.0
7978
20151110.0
7979
20151113.0
7980
20151116.0
7981
20151119.0
7982
20151122.0
7983
20151125.0
7984
20151128.0
7985
20151201.0
7986
20151204.0
7987
20151207.0
7988
20151210.0
7989
20151213.0
7990
20151216.0
7991
20151219.0
7992
20151222.0
7993
20151225.0
7994
20151228.0
7995
20151231.0
7996
20160103.0
7997
20160106.0
7998
20160109.0
7999
20160112.0
8000
20160115.0
8001
20160118.0
8002
20160121.0
8003
20160124.0
8004
20160127.0
8005
20160130.0
8006
20160202.0
8007
20160205.0
8008
20160208.0
8009
20160211.0
8010
20160214.0
8011
20160217.0
8012
20160220.0
8013
20160223.0
8014
20160226.0
8015
20160229.0
8016
20160303.0
8017
20160306.0
8018
20160309.0
8019
20160312.0
8020
20160315.0
8021
20160318.0
8022
20160321.0
8023
20160324.0
8024
20160327.0
8025
20160330.0
8026
20160402.0
8027
20160405.0
8028
20160408.0
8029
20160411.0
8030
20160414.0
8031
20160417.0
8032
201

In [2]:
#计算时间
def start_end_time(date_time):
    #data_time=np.array(data.variables['time'])
    start_time=datetime.datetime(1900,1,1,0,0)
    transtime1=start_time+datetime.timedelta(hours=int(date_time))
    print('start time:',transtime1)
    return 

In [3]:
#使用最初的数据，即没有任何改变，只是经过grib转换，经纬度变化的模式数据
#ecmf数据 2006年7月8日数据
ecmf_olr=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/use_s2s_data/grib_to_nc/remap_ecmf/OLR/10_ecmf_20060708_ttr.nc')
time_ecmf_olr=np.array(ecmf_olr.variables['time'])
data_ecmf_olr=np.array(ecmf_olr.variables['ttr'])

In [4]:
print(data_ecmf_olr.shape)

(47, 11, 13, 144)


In [5]:
#输出ecmf时间，以及其对应的部分数据
for i in range(0,len(time_ecmf_olr)):
    start_end_time(time_ecmf_olr[i])
    #print(data_ecmf_olr[i,:,2,7])

start time: 2006-07-08 00:00:00
start time: 2006-07-09 00:00:00
start time: 2006-07-10 00:00:00
start time: 2006-07-11 00:00:00
start time: 2006-07-12 00:00:00
start time: 2006-07-13 00:00:00
start time: 2006-07-14 00:00:00
start time: 2006-07-15 00:00:00
start time: 2006-07-16 00:00:00
start time: 2006-07-17 00:00:00
start time: 2006-07-18 00:00:00
start time: 2006-07-19 00:00:00
start time: 2006-07-20 00:00:00
start time: 2006-07-21 00:00:00
start time: 2006-07-22 00:00:00
start time: 2006-07-23 00:00:00
start time: 2006-07-24 00:00:00
start time: 2006-07-25 00:00:00
start time: 2006-07-26 00:00:00
start time: 2006-07-27 00:00:00
start time: 2006-07-28 00:00:00
start time: 2006-07-29 00:00:00
start time: 2006-07-30 00:00:00
start time: 2006-07-31 00:00:00
start time: 2006-08-01 00:00:00
start time: 2006-08-02 00:00:00
start time: 2006-08-03 00:00:00
start time: 2006-08-04 00:00:00
start time: 2006-08-05 00:00:00
start time: 2006-08-06 00:00:00
start time: 2006-08-07 00:00:00
start ti

In [6]:
#babj数据 2006年7月8日数据
babj_olr=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/use_s2s_data/grib_to_nc/remap_babj/OLR/10_babj_20060708_ttr.nc')
time_babj_olr=np.array(babj_olr.variables['time'])
data_babj_olr=np.array(babj_olr.variables['ttr'])

In [7]:
print(data_babj_olr.shape)

(60, 4, 13, 144)


In [8]:
#输出babj时间，以及其对应的部分数据
for i in range(0,len(time_babj_olr)):
    start_end_time(time_babj_olr[i])
    #print(data_ecmf_olr[i,:,2,7])

start time: 2006-07-09 00:00:00
start time: 2006-07-10 00:00:00
start time: 2006-07-11 00:00:00
start time: 2006-07-12 00:00:00
start time: 2006-07-13 00:00:00
start time: 2006-07-14 00:00:00
start time: 2006-07-15 00:00:00
start time: 2006-07-16 00:00:00
start time: 2006-07-17 00:00:00
start time: 2006-07-18 00:00:00
start time: 2006-07-19 00:00:00
start time: 2006-07-20 00:00:00
start time: 2006-07-21 00:00:00
start time: 2006-07-22 00:00:00
start time: 2006-07-23 00:00:00
start time: 2006-07-24 00:00:00
start time: 2006-07-25 00:00:00
start time: 2006-07-26 00:00:00
start time: 2006-07-27 00:00:00
start time: 2006-07-28 00:00:00
start time: 2006-07-29 00:00:00
start time: 2006-07-30 00:00:00
start time: 2006-07-31 00:00:00
start time: 2006-08-01 00:00:00
start time: 2006-08-02 00:00:00
start time: 2006-08-03 00:00:00
start time: 2006-08-04 00:00:00
start time: 2006-08-05 00:00:00
start time: 2006-08-06 00:00:00
start time: 2006-08-07 00:00:00
start time: 2006-08-08 00:00:00
start ti

In [9]:
#babj数据和ecmf数据做对比
#7月8日都没有，是0
#从7月9号开始
print("date: 2006.07.09~2006.07.19:")
print("ecmf data olr:")
print(data_ecmf_olr[1:11,0,2,7])
print("babj data olr:")
print(data_babj_olr[0:10,0,2,7])

date: 2006.07.09~2006.07.19:
ecmf data olr:
[-2.58811587e+07 -5.18457378e+07 -7.73932152e+07 -1.01877083e+08
 -1.26757198e+08 -1.51512182e+08 -1.76705123e+08 -2.01626948e+08
 -2.26152526e+08 -2.51303757e+08]
babj data olr:
[-2.60832334e+07 -5.19708714e+07 -7.77771018e+07 -1.03610468e+08
 -1.29281019e+08 -1.55060114e+08 -1.81029159e+08 -2.07025341e+08
 -2.33347153e+08 -2.59696101e+08]


In [10]:
print(data_ecmf_olr[1:,:,2,7])

[[-2.58811587e+07 -2.59854341e+07 -2.58185935e+07 -2.59645791e+07
  -2.57560282e+07 -2.57768833e+07 -2.60271443e+07 -2.58603036e+07
  -2.59228689e+07 -2.59020138e+07 -2.58811587e+07]
 [-5.18457378e+07 -5.21168539e+07 -5.16997522e+07 -5.19917234e+07
  -5.14912013e+07 -5.16788971e+07 -5.21377089e+07 -5.16788971e+07
  -5.19083030e+07 -5.17206073e+07 -5.18457378e+07]
 [-7.73932152e+07 -7.78520270e+07 -7.68092728e+07 -7.74766355e+07
  -7.68301279e+07 -7.72055194e+07 -7.78728821e+07 -7.72472296e+07
  -7.75392007e+07 -7.67675626e+07 -7.70386787e+07]
 [-1.01877083e+08 -1.02773852e+08 -1.01063735e+08 -1.02148199e+08
  -1.01877083e+08 -1.02085634e+08 -1.03170098e+08 -1.01835373e+08
  -1.02294185e+08 -1.01147155e+08 -1.01459982e+08]
 [-1.26757198e+08 -1.27320285e+08 -1.25339052e+08 -1.26882328e+08
  -1.26944894e+08 -1.27132589e+08 -1.28446460e+08 -1.26632067e+08
  -1.26986604e+08 -1.25797864e+08 -1.26381806e+08]
 [-1.51512182e+08 -1.52012704e+08 -1.50177457e+08 -1.51428762e+08
  -1.51366197e+08 -

In [11]:
print(data_babj_olr[0:,:,2,7])

[[-2.60832334e+07 -2.60832334e+07 -2.60832334e+07 -2.60832334e+07]
 [-5.19708714e+07 -5.19437355e+07 -5.19708714e+07 -5.19437355e+07]
 [-7.77771018e+07 -7.77771018e+07 -7.78042377e+07 -7.77771018e+07]
 [-1.03610468e+08 -1.03610468e+08 -1.03664740e+08 -1.03583332e+08]
 [-1.29281019e+08 -1.29091068e+08 -1.29308155e+08 -1.29172475e+08]
 [-1.55060114e+08 -1.54788755e+08 -1.55141521e+08 -1.54924434e+08]
 [-1.81029159e+08 -1.80839208e+08 -1.81137703e+08 -1.80974887e+08]
 [-2.07025341e+08 -2.07133884e+08 -2.07215292e+08 -2.07188156e+08]
 [-2.33347153e+08 -2.33618512e+08 -2.33102930e+08 -2.33455697e+08]
 [-2.59696101e+08 -2.60076004e+08 -2.58963432e+08 -2.59750373e+08]
 [-2.85665147e+08 -2.86099321e+08 -2.85068157e+08 -2.85638011e+08]
 [-3.11607057e+08 -3.12014095e+08 -3.11362834e+08 -3.11715600e+08]
 [-3.37413287e+08 -3.37766054e+08 -3.37250472e+08 -3.37793190e+08]
 [-3.62921023e+08 -3.63083838e+08 -3.63138110e+08 -3.63463741e+08]
 [-3.87316187e+08 -3.88401623e+08 -3.88537302e+08 -3.88890069e

In [12]:
#看u200
ecmf_u200=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/use_s2s_data/grib_to_nc/remap_ecmf/U200/10_ecmf_20060708_u200.nc')
time_ecmf_u200=np.array(ecmf_u200.variables['time'])
data_ecmf_u200=np.array(ecmf_u200.variables['u200'])

In [13]:
print(data_ecmf_u200.shape)

(46, 11, 13, 144)


In [14]:
for i in range(0,len(time_ecmf_u200)):
    start_end_time(time_ecmf_u200[i])

start time: 2006-07-08 00:00:00
start time: 2006-07-09 00:00:00
start time: 2006-07-10 00:00:00
start time: 2006-07-11 00:00:00
start time: 2006-07-12 00:00:00
start time: 2006-07-13 00:00:00
start time: 2006-07-14 00:00:00
start time: 2006-07-15 00:00:00
start time: 2006-07-16 00:00:00
start time: 2006-07-17 00:00:00
start time: 2006-07-18 00:00:00
start time: 2006-07-19 00:00:00
start time: 2006-07-20 00:00:00
start time: 2006-07-21 00:00:00
start time: 2006-07-22 00:00:00
start time: 2006-07-23 00:00:00
start time: 2006-07-24 00:00:00
start time: 2006-07-25 00:00:00
start time: 2006-07-26 00:00:00
start time: 2006-07-27 00:00:00
start time: 2006-07-28 00:00:00
start time: 2006-07-29 00:00:00
start time: 2006-07-30 00:00:00
start time: 2006-07-31 00:00:00
start time: 2006-08-01 00:00:00
start time: 2006-08-02 00:00:00
start time: 2006-08-03 00:00:00
start time: 2006-08-04 00:00:00
start time: 2006-08-05 00:00:00
start time: 2006-08-06 00:00:00
start time: 2006-08-07 00:00:00
start ti

In [15]:
#看u200
babj_u200=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/use_s2s_data/grib_to_nc/remap_babj/U200/10_babj_20060708_u200.nc')
time_babj_u200=np.array(babj_u200.variables['time'])
data_babj_u200=np.array(babj_u200.variables['u200'])

In [16]:
print(data_babj_u200.shape)

(60, 4, 13, 144)


In [17]:
for i in range(0,len(time_babj_u200)):
    start_end_time(time_babj_u200[i])

start time: 2006-07-08 00:00:00
start time: 2006-07-09 00:00:00
start time: 2006-07-10 00:00:00
start time: 2006-07-11 00:00:00
start time: 2006-07-12 00:00:00
start time: 2006-07-13 00:00:00
start time: 2006-07-14 00:00:00
start time: 2006-07-15 00:00:00
start time: 2006-07-16 00:00:00
start time: 2006-07-17 00:00:00
start time: 2006-07-18 00:00:00
start time: 2006-07-19 00:00:00
start time: 2006-07-20 00:00:00
start time: 2006-07-21 00:00:00
start time: 2006-07-22 00:00:00
start time: 2006-07-23 00:00:00
start time: 2006-07-24 00:00:00
start time: 2006-07-25 00:00:00
start time: 2006-07-26 00:00:00
start time: 2006-07-27 00:00:00
start time: 2006-07-28 00:00:00
start time: 2006-07-29 00:00:00
start time: 2006-07-30 00:00:00
start time: 2006-07-31 00:00:00
start time: 2006-08-01 00:00:00
start time: 2006-08-02 00:00:00
start time: 2006-08-03 00:00:00
start time: 2006-08-04 00:00:00
start time: 2006-08-05 00:00:00
start time: 2006-08-06 00:00:00
start time: 2006-08-07 00:00:00
start ti

In [18]:
#u200的模式数据逐日对比
#从7月8号开始
print("date: 2006.07.08~2006.07.19:")
print("ecmf data u200:")
mean_data_ecmf_u200=np.mean(data_ecmf_u200,axis=1)
mean_data_babj_u200=np.mean(data_babj_u200,axis=1)
print(mean_data_ecmf_u200[0:10,2,7])
print("babj data u200:")
print(mean_data_babj_u200[0:10,2,7])

date: 2006.07.08~2006.07.19:
ecmf data u200:
[ 3.8434324  0.5127185  6.429027  10.748287  11.111243  11.728189
 12.912628  13.455628   9.370109   5.343527 ]
babj data u200:
[ 5.2321377  1.098209   3.8347886  7.4395533  7.743316   7.1056657
 13.728107  12.772066   9.113253   3.1084116]


In [19]:
#载入再分析数据的u200看看
re_u200=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/new_DATA/u200_1950-2022.nc')
time_re_u200=np.array(re_u200.variables['time'])
data_re_u200=np.array(re_u200.variables['u200'])

In [20]:
print(data_re_u200.shape)

(26329, 13, 144)


In [21]:
#找到再分析数据从20006年7月8日开始的数据
start_end_time(time_re_u200[20642])
print(data_re_u200[20642:20652,2,7])

start time: 2006-07-08 00:00:00
[ 3.395613   1.8619552  4.020651   9.075934  12.568623  18.280775
 20.202187  23.35342    9.246662   3.8846471]


In [22]:
#没有平均样本的比较
print("ecmf data u200")
print(data_ecmf_u200[0:10,:,2,7])
print("babj data u200:")
print(data_babj_u200[0:10,:,2,7])

ecmf data u200
[[ 3.83175898e+00  5.09660053e+00  2.56876731e+00  3.46836662e+00
   4.24214792e+00  3.82065725e+00  3.87616515e+00  2.46663284e+00
   5.20317602e+00  3.90947008e+00  3.79401326e+00]
 [ 1.76373795e-01  1.83236170e+00 -3.82570364e-02  5.31254768e-01
   4.27639902e-01  1.50306290e-02  4.41331863e-01  3.33646387e-01
   1.11778903e+00  6.58923090e-01  1.43809125e-01]
 [ 6.14237070e+00  7.45531940e+00  6.91726208e+00  6.19824886e+00
   4.06452227e+00  6.56275129e+00  6.67783785e+00  5.49366760e+00
   7.25067997e+00  4.77872515e+00  9.17791653e+00]
 [ 1.19573860e+01  1.50125456e+01  4.57371569e+00  7.87829018e+00
   1.12761183e+01  1.08390856e+01  1.53170986e+01  1.51131992e+01
   1.25727844e+01  8.26462555e+00  5.42631817e+00]
 [ 1.47264938e+01  9.47284889e+00  1.05537748e+01  6.67265701e+00
   1.35179005e+01  1.42517157e+01  1.27455997e+01  1.22349262e+01
   1.22234545e+01  6.41361952e+00  9.41067982e+00]
 [ 1.30919695e+01  1.37861891e+01  3.57827234e+00  1.15506973e+01
   1

In [23]:
#看u850
ecmf_u850=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/use_s2s_data/grib_to_nc/remap_ecmf/U850/10_ecmf_20060708_u850.nc')
time_ecmf_u850=np.array(ecmf_u850.variables['time'])
data_ecmf_u850=np.array(ecmf_u850.variables['u850'])

In [24]:
print(data_ecmf_u850.shape)

(46, 11, 13, 144)


In [25]:
for i in range(0,len(time_ecmf_u850)):
    start_end_time(time_ecmf_u850[i])

start time: 2006-07-08 00:00:00
start time: 2006-07-09 00:00:00
start time: 2006-07-10 00:00:00
start time: 2006-07-11 00:00:00
start time: 2006-07-12 00:00:00
start time: 2006-07-13 00:00:00
start time: 2006-07-14 00:00:00
start time: 2006-07-15 00:00:00
start time: 2006-07-16 00:00:00
start time: 2006-07-17 00:00:00
start time: 2006-07-18 00:00:00
start time: 2006-07-19 00:00:00
start time: 2006-07-20 00:00:00
start time: 2006-07-21 00:00:00
start time: 2006-07-22 00:00:00
start time: 2006-07-23 00:00:00
start time: 2006-07-24 00:00:00
start time: 2006-07-25 00:00:00
start time: 2006-07-26 00:00:00
start time: 2006-07-27 00:00:00
start time: 2006-07-28 00:00:00
start time: 2006-07-29 00:00:00
start time: 2006-07-30 00:00:00
start time: 2006-07-31 00:00:00
start time: 2006-08-01 00:00:00
start time: 2006-08-02 00:00:00
start time: 2006-08-03 00:00:00
start time: 2006-08-04 00:00:00
start time: 2006-08-05 00:00:00
start time: 2006-08-06 00:00:00
start time: 2006-08-07 00:00:00
start ti

In [26]:
#看u850
babj_u850=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/use_s2s_data/grib_to_nc/remap_babj/U850/10_babj_20060708_u850.nc')
time_babj_u850=np.array(babj_u850.variables['time'])
data_babj_u850=np.array(babj_u850.variables['u850'])

In [27]:
print(data_babj_u850.shape)

(60, 4, 13, 144)


In [28]:
for i in range(0,len(time_babj_u850)):
    start_end_time(time_babj_u850[i])

start time: 2006-07-08 00:00:00
start time: 2006-07-09 00:00:00
start time: 2006-07-10 00:00:00
start time: 2006-07-11 00:00:00
start time: 2006-07-12 00:00:00
start time: 2006-07-13 00:00:00
start time: 2006-07-14 00:00:00
start time: 2006-07-15 00:00:00
start time: 2006-07-16 00:00:00
start time: 2006-07-17 00:00:00
start time: 2006-07-18 00:00:00
start time: 2006-07-19 00:00:00
start time: 2006-07-20 00:00:00
start time: 2006-07-21 00:00:00
start time: 2006-07-22 00:00:00
start time: 2006-07-23 00:00:00
start time: 2006-07-24 00:00:00
start time: 2006-07-25 00:00:00
start time: 2006-07-26 00:00:00
start time: 2006-07-27 00:00:00
start time: 2006-07-28 00:00:00
start time: 2006-07-29 00:00:00
start time: 2006-07-30 00:00:00
start time: 2006-07-31 00:00:00
start time: 2006-08-01 00:00:00
start time: 2006-08-02 00:00:00
start time: 2006-08-03 00:00:00
start time: 2006-08-04 00:00:00
start time: 2006-08-05 00:00:00
start time: 2006-08-06 00:00:00
start time: 2006-08-07 00:00:00
start ti

In [29]:
re_u850=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/new_DATA/u850_1950-2022.nc')
time_re_u850=np.array(re_u850.variables['time'])
data_re_u850=np.array(re_u850.variables['u850'])

In [30]:
#找到再分析数据从20006年7月8日开始的数据
start_end_time(time_re_u850[20642])
print(data_re_u850[20642:20652,2,7])

start time: 2006-07-08 00:00:00
[ -3.480784  -14.5722275 -12.972244  -10.613211   -6.618786   -3.3989038
  -2.9563081  -3.4320984   1.9100293   1.8901125]


In [31]:
#u200的模式数据逐日对比，平均了样本
#从7月8号开始
print("date: 2006.07.08~2006.07.19:")
print("ecmf data u850:")
mean_data_ecmf_u850=np.mean(data_ecmf_u850,axis=1)
mean_data_babj_u850=np.mean(data_babj_u850,axis=1)
print(mean_data_ecmf_u850[0:10,2,7])
print("babj data u850:")
print(mean_data_babj_u850[0:10,2,7])

date: 2006.07.08~2006.07.19:
ecmf data u850:
[ -3.5659406  -8.899617  -10.97972    -9.030818   -4.330773   -3.3237908
  -3.1041136  -1.0671729  -1.7080041  -2.0696805]
babj data u850:
[-4.107511  -8.135083  -7.100681  -7.0372353 -1.862512   0.6333625
  0.6639713 -0.9037599 -2.1893284 -3.9567914]


In [32]:
#没有平均样本的比较
print("ecmf data u850")
print(data_ecmf_u850[0:10,:,2,7])
print("babj data u850:")
print(data_babj_u850[0:10,:,2,7])

ecmf data u850
[[ -3.5711548   -4.3867517   -2.718182    -2.781091    -4.3264327
   -3.0645518   -4.0655456   -3.428684    -3.7513702   -3.9730322
   -3.1585453 ]
 [ -8.932855   -10.117764   -10.736494    -9.45796     -9.369887
   -9.931998    -9.398752    -7.660612    -8.007352    -6.155976
   -8.126139  ]
 [-10.969257   -11.028835   -11.06214    -10.63732    -11.757841
  -10.2102785  -11.076572   -10.030803   -10.806434   -10.989241
  -12.208195  ]
 [ -9.527901    -9.131204    -7.7475743   -4.5547557   -9.66223
   -8.97356    -10.426019    -9.760664   -10.324625    -9.622634
   -9.607832  ]
 [ -3.5829961   -2.5105822   -2.711151    -4.7616158   -3.457178
   -7.3856626   -4.344936    -5.9431953   -1.959573    -4.5510554
   -6.4305553 ]
 [ -0.44753584  -1.0381407   -7.2176585   -0.14187193   0.03760385
   -5.7774115   -5.578323    -4.980317    -6.567105    -1.1476765
   -3.7032635 ]
 [ -0.26435944  -0.5814951   -6.386149    -6.288455    -6.4372163
   -0.4667786   -0.6125795   -2.227121

In [33]:
#看sst
ecmf_sst=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/use_s2s_data/grib_to_nc/remap_ecmf/SST/10_ecmf_20060708_sst.nc')
time_ecmf_sst=np.array(ecmf_sst.variables['time'])
data_ecmf_sst=np.array(ecmf_sst.variables['sst'])

In [34]:
print(data_ecmf_sst.shape)

(46, 11, 13, 144)


In [35]:
for i in range(0,len(time_ecmf_sst)):
    start_end_time(time_ecmf_sst[i])

start time: 2006-07-08 00:00:00
start time: 2006-07-09 00:00:00
start time: 2006-07-10 00:00:00
start time: 2006-07-11 00:00:00
start time: 2006-07-12 00:00:00
start time: 2006-07-13 00:00:00
start time: 2006-07-14 00:00:00
start time: 2006-07-15 00:00:00
start time: 2006-07-16 00:00:00
start time: 2006-07-17 00:00:00
start time: 2006-07-18 00:00:00
start time: 2006-07-19 00:00:00
start time: 2006-07-20 00:00:00
start time: 2006-07-21 00:00:00
start time: 2006-07-22 00:00:00
start time: 2006-07-23 00:00:00
start time: 2006-07-24 00:00:00
start time: 2006-07-25 00:00:00
start time: 2006-07-26 00:00:00
start time: 2006-07-27 00:00:00
start time: 2006-07-28 00:00:00
start time: 2006-07-29 00:00:00
start time: 2006-07-30 00:00:00
start time: 2006-07-31 00:00:00
start time: 2006-08-01 00:00:00
start time: 2006-08-02 00:00:00
start time: 2006-08-03 00:00:00
start time: 2006-08-04 00:00:00
start time: 2006-08-05 00:00:00
start time: 2006-08-06 00:00:00
start time: 2006-08-07 00:00:00
start ti

In [36]:
#看sst
babj_sst=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/use_s2s_data/grib_to_nc/remap_babj/SST/10_babj_20060708_sst.nc')
time_babj_sst=np.array(babj_sst.variables['time'])
data_babj_sst=np.array(babj_sst.variables['sst'])

In [37]:
print(data_babj_sst.shape)

(60, 4, 13, 144)


In [38]:
for i in range(0,len(time_babj_sst)):
    start_end_time(time_babj_sst[i])

start time: 2006-07-08 00:00:00
start time: 2006-07-09 00:00:00
start time: 2006-07-10 00:00:00
start time: 2006-07-11 00:00:00
start time: 2006-07-12 00:00:00
start time: 2006-07-13 00:00:00
start time: 2006-07-14 00:00:00
start time: 2006-07-15 00:00:00
start time: 2006-07-16 00:00:00
start time: 2006-07-17 00:00:00
start time: 2006-07-18 00:00:00
start time: 2006-07-19 00:00:00
start time: 2006-07-20 00:00:00
start time: 2006-07-21 00:00:00
start time: 2006-07-22 00:00:00
start time: 2006-07-23 00:00:00
start time: 2006-07-24 00:00:00
start time: 2006-07-25 00:00:00
start time: 2006-07-26 00:00:00
start time: 2006-07-27 00:00:00
start time: 2006-07-28 00:00:00
start time: 2006-07-29 00:00:00
start time: 2006-07-30 00:00:00
start time: 2006-07-31 00:00:00
start time: 2006-08-01 00:00:00
start time: 2006-08-02 00:00:00
start time: 2006-08-03 00:00:00
start time: 2006-08-04 00:00:00
start time: 2006-08-05 00:00:00
start time: 2006-08-06 00:00:00
start time: 2006-08-07 00:00:00
start ti

In [39]:
re_sst=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/new_DATA/sst_1950-2022.nc')
time_re_sst=np.array(re_sst.variables['time'])
data_re_sst=np.array(re_sst.variables['sst'])

In [40]:
#找到再分析数据从20006年7月8日开始的数据
start_end_time(time_re_sst[20642])
print(data_re_sst[20642:20652,2,17])

start time: 2006-07-08 00:00:00
[299.38513 299.31186 299.23444 299.1508  299.05817 298.9683  298.90262
 298.86322 298.85492 298.8805 ]


In [41]:
#u200的模式数据逐日对比，平均了样本
#从7月8号开始
print("date: 2006.07.08~2006.07.19:")
print("ecmf data sst:")
mean_data_ecmf_sst=np.mean(data_ecmf_sst,axis=1)
mean_data_babj_sst=np.mean(data_babj_sst,axis=1)
print(mean_data_ecmf_sst[0:10,2,17])
print("babj data sst:")
print(mean_data_babj_sst[0:10,2,17])

date: 2006.07.08~2006.07.19:
ecmf data sst:
[299.17544787 299.10895241 299.08921896 299.04544847 299.03726118
 299.04214207 299.05778188 299.03017603 299.02020434 299.01101988]
babj data sst:
[298.99981689 298.99981689 298.99981689 298.99981689 298.99981689
 298.99981689 298.33312987 298.33312987 298.33312987 298.38877359]


In [42]:
#没有平均样本的比较
print("ecmf data sst")
print(data_ecmf_sst[0:10,:,2,17])
print("babj data sst:")
print(data_babj_sst[0:10,:,2,17])

ecmf data sst
[[299.16589603 299.1168248  299.2848216  299.06544434 299.24441
  299.16012295 299.15550448 299.24441    299.06486703 299.27962583
  299.14799947]
 [299.10239209 299.06313511 299.1705145  298.99674462 299.17975144
  299.12028866 299.0896913  299.17397835 298.99732193 299.18494722
  299.11971135]
 [299.1098971  299.02445543 299.18206067 298.95171455 299.13991715
  299.11971135 299.06833088 299.17975144 298.97422958 299.1503087
  299.08103167]
 [299.07006281 299.02445543 299.08507283 298.9014887  299.09084592
  299.08853668 299.03484698 299.08449552 298.93439529 299.13241214
  299.05332086]
 [299.06659896 299.00829079 299.0625578  298.89917947 299.09026861
  299.10412402 299.01406388 299.03657891 298.95286917 299.13587599
  299.03946545]
 [299.09084592 299.05736202 299.00367232 298.93439529 299.07294935
  299.12490712 299.00713617 298.9886623  298.94651877 299.17340105
  299.06371241]
 [299.11393826 299.05101163 299.00771348 298.93093144 299.05043432
  299.2172765  299.0388

In [59]:
print("ecmf data olr:")
print(data_ecmf_olr[0:10,0,2,7])
print("babj data olr:")
print(data_babj_olr[0:10,0,2,7])

ecmf data olr:
[ 0.00000000e+00 -2.58811587e+07 -5.18457378e+07 -7.73932152e+07
 -1.01877083e+08 -1.26757198e+08 -1.51512182e+08 -1.76705123e+08
 -2.01626948e+08 -2.26152526e+08]
babj data olr:
[-2.60832334e+07 -5.19708714e+07 -7.77771018e+07 -1.03610468e+08
 -1.29281019e+08 -1.55060114e+08 -1.81029159e+08 -2.07025341e+08
 -2.33347153e+08 -2.59696101e+08]


In [60]:
print(data_ecmf_olr[2,0,2,7]-data_ecmf_olr[1,0,2,7])

-25964579.052385807


In [54]:
#去除模式数据的累加，再除以86400，得到W/s的值
def delete_add(data):
    #创建一个新数组，和data一样大小
    new_data=np.zeros(data.shape)
    new_data[0,:,:,:]=data[0,:,:,:]
    for i in range(1,len(data)):
        new_data[i,:,:,:]=data[i,:,:,:]-data[i-1,:,:,:]
    print(new_data[0:10,0,2,7])
    #new_data=np.true_divide(new_data,86400)
    return new_data

In [55]:
new_data_ecmf_olr=delete_add(data_ecmf_olr)
new_data_babj_olr=delete_add(data_babj_olr)
print(new_data_ecmf_olr.shape,new_data_babj_olr.shape)

[        0.         -25881158.718081   -25964579.05238581
 -25547477.38086152 -24483868.11847472 -24880114.70642269
 -24754984.20496541 -25192940.96006596 -24921824.87357509
 -24525578.28562713]
[-26083233.36960006 -25887638.05014277 -25806230.38331831
 -25833366.27225971 -25670550.93861115 -25779094.4943769
 -25969045.71696699 -25996181.60590851 -26321812.27320576
 -26348948.1621474 ]
(47, 11, 13, 144) (60, 4, 13, 144)


In [56]:
#载入再分析数据的olr看看
re_olr=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/new_DATA/olr_1950-2022.nc')
time_re_olr=np.array(re_olr.variables['time'])
data_re_olr=np.array(re_olr.variables['olr'])

In [57]:
#找到再分析数据从20006年7月8日开始的数据
start_end_time(time_re_olr[20642])
print(data_re_olr[20642:20652,2,7])

start time: 2006-07-08 00:00:00
[-289.36526 -295.61404 -295.45477 -288.6326  -286.8275  -286.61514
 -285.2454  -273.73532 -284.85254 -284.61893]


In [61]:
#模式数据的olr
print("ecmf olr data:")
print(new_data_ecmf_olr[1:9,0,2,7]/86400)
print("babj olr data:")
print(new_data_babj_olr[0:9,0,2,7]/86400)

ecmf olr data:
[-299.55044813 -300.51596125 -295.68839561 -283.37810322 -287.96429058
 -286.51602089 -291.58496482 -288.44704715]
babj olr data:
[-301.88927511 -299.6254404  -298.68322203 -298.99729482 -297.11285809
 -298.36914924 -300.56765876 -300.88173155 -304.65060501]


In [62]:
#模式数据气候态
season_re_olr=np.load('/WdHeDisk/users/zhangnong/MJO/new_DATA/climatology_seasonal_cycle_olr_sample.npy')
season_re_u200=np.load('/WdHeDisk/users/zhangnong/MJO/new_DATA/climatology_seasonal_cycle_u200_sample.npy')
season_re_u850=np.load('/WdHeDisk/users/zhangnong/MJO/new_DATA/climatology_seasonal_cycle_u850_sample.npy')
print(season_re_olr.shape,season_re_u200.shape,season_re_u850.shape)

(26329, 13, 144) (26329, 13, 144) (26329, 13, 144)


In [63]:
print(season_re_olr[20642:20652,2,7])

[-283.27063 -281.76178 -283.05154 -282.52362 -279.75638 -282.71796
 -282.4459  -282.21658 -281.74197 -277.7626 ]


In [64]:
print(season_re_u200[20642:20652,2,7])

[5.928077  5.0788746 4.873712  4.4770827 4.956472  5.060934  4.382748
 3.6790986 2.1512284 2.1741846]


In [65]:
print(season_re_u850[20642:20652,2,7])

[-7.714874  -8.4082    -7.7035885 -6.1658635 -5.43241   -5.4204583
 -4.8124065 -4.9483566 -5.3704453 -4.924531 ]


In [66]:
print(data_re_olr[20642:20652,2,7])

[-289.36526 -295.61404 -295.45477 -288.6326  -286.8275  -286.61514
 -285.2454  -273.73532 -284.85254 -284.61893]


In [67]:
print(data_re_u200[20642:20652,2,7])

[ 3.395613   1.8619552  4.020651   9.075934  12.568623  18.280775
 20.202187  23.35342    9.246662   3.8846471]


In [68]:
print(data_re_u850[20642:20652,2,7])

[ -3.480784  -14.5722275 -12.972244  -10.613211   -6.618786   -3.3989038
  -2.9563081  -3.4320984   1.9100293   1.8901125]


In [69]:
print(data_re_olr[20642:20652,2,7]-season_re_olr[20642:20652,2,7])
print("---------")
print(data_re_u200[20642:20652,2,7]-season_re_u200[20642:20652,2,7])
print("---------")
print(data_re_u850[20642:20652,2,7]-season_re_u850[20642:20652,2,7])

[ -6.094635  -13.852264  -12.403229   -6.1089783  -7.0711365  -3.8971863
  -2.7994995   8.481262   -3.1105652  -6.8563232]
---------
[-2.5324643 -3.2169194 -0.8530612  4.5988517  7.6121507 13.219841
 15.819439  19.674322   7.0954337  1.7104626]
---------
[ 4.23409   -6.164027  -5.268656  -4.447347  -1.1863761  2.0215545
  1.8560984  1.5162582  7.2804747  6.8146434]


In [76]:
#ncep的olr数据
ncep_olr01=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/NCEP_data/10_s2s_kwbc_2022_20220101_ttr.nc')
ncep_olr02=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/NCEP_data/10_s2s_kwbc_2022_20220102_ttr.nc')
ncep_olr03=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/NCEP_data/10_s2s_kwbc_2022_20220103_ttr.nc')
ncep_olr04=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/NCEP_data/10_s2s_kwbc_2022_20220104_ttr.nc')
ncep_olr05=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/NCEP_data/10_s2s_kwbc_2022_20220105_ttr.nc')
time_ncep_olr01=np.array(ncep_olr01.variables['time'])
time_ncep_olr02=np.array(ncep_olr02.variables['time'])
time_ncep_olr03=np.array(ncep_olr03.variables['time'])
time_ncep_olr04=np.array(ncep_olr04.variables['time'])
time_ncep_olr05=np.array(ncep_olr05.variables['time'])
data_ncep_olr01=np.array(ncep_olr01.variables['ttr'])
data_ncep_olr02=np.array(ncep_olr02.variables['ttr'])
data_ncep_olr03=np.array(ncep_olr03.variables['ttr'])
data_ncep_olr04=np.array(ncep_olr04.variables['ttr'])
data_ncep_olr05=np.array(ncep_olr05.variables['ttr'])

In [77]:
for i in range(0,len(time_ncep_olr01)):
    start_end_time(time_ncep_olr01[i])

start time: 2022-01-02 00:00:00
start time: 2022-01-03 00:00:00
start time: 2022-01-04 00:00:00
start time: 2022-01-05 00:00:00
start time: 2022-01-06 00:00:00
start time: 2022-01-07 00:00:00
start time: 2022-01-08 00:00:00
start time: 2022-01-09 00:00:00
start time: 2022-01-10 00:00:00
start time: 2022-01-11 00:00:00
start time: 2022-01-12 00:00:00
start time: 2022-01-13 00:00:00
start time: 2022-01-14 00:00:00
start time: 2022-01-15 00:00:00
start time: 2022-01-16 00:00:00
start time: 2022-01-17 00:00:00
start time: 2022-01-18 00:00:00
start time: 2022-01-19 00:00:00
start time: 2022-01-20 00:00:00
start time: 2022-01-21 00:00:00
start time: 2022-01-22 00:00:00
start time: 2022-01-23 00:00:00
start time: 2022-01-24 00:00:00
start time: 2022-01-25 00:00:00
start time: 2022-01-26 00:00:00
start time: 2022-01-27 00:00:00
start time: 2022-01-28 00:00:00
start time: 2022-01-29 00:00:00
start time: 2022-01-30 00:00:00
start time: 2022-01-31 00:00:00
start time: 2022-02-01 00:00:00
start ti

In [78]:
for i in range(0,len(time_ncep_olr02)):
    start_end_time(time_ncep_olr02[i])

start time: 2022-01-03 00:00:00
start time: 2022-01-04 00:00:00
start time: 2022-01-05 00:00:00
start time: 2022-01-06 00:00:00
start time: 2022-01-07 00:00:00
start time: 2022-01-08 00:00:00
start time: 2022-01-09 00:00:00
start time: 2022-01-10 00:00:00
start time: 2022-01-11 00:00:00
start time: 2022-01-12 00:00:00
start time: 2022-01-13 00:00:00
start time: 2022-01-14 00:00:00
start time: 2022-01-15 00:00:00
start time: 2022-01-16 00:00:00
start time: 2022-01-17 00:00:00
start time: 2022-01-18 00:00:00
start time: 2022-01-19 00:00:00
start time: 2022-01-20 00:00:00
start time: 2022-01-21 00:00:00
start time: 2022-01-22 00:00:00
start time: 2022-01-23 00:00:00
start time: 2022-01-24 00:00:00
start time: 2022-01-25 00:00:00
start time: 2022-01-26 00:00:00
start time: 2022-01-27 00:00:00
start time: 2022-01-28 00:00:00
start time: 2022-01-29 00:00:00
start time: 2022-01-30 00:00:00
start time: 2022-01-31 00:00:00
start time: 2022-02-01 00:00:00
start time: 2022-02-02 00:00:00
start ti

In [79]:
start_end_time(time_ncep_olr01[4])
start_end_time(time_ncep_olr02[3])
start_end_time(time_ncep_olr03[2])
start_end_time(time_ncep_olr04[1])
start_end_time(time_ncep_olr05[0])

start time: 2022-01-06 00:00:00
start time: 2022-01-06 00:00:00
start time: 2022-01-06 00:00:00
start time: 2022-01-06 00:00:00
start time: 2022-01-06 00:00:00


In [80]:
print("2022.01.01:")
print(data_ncep_olr01[4:14,0,2,7])
print("2022.01.02:")
print(data_ncep_olr02[3:13,0,2,7])
print("2022.01.03:")
print(data_ncep_olr03[2:12,0,2,7])
print("2022.01.04:")
print(data_ncep_olr04[1:11,0,2,7])
print("2022.01.05:")
print(data_ncep_olr05[0:10,0,2,7])

2022.01.01:
[-9.96396146e+07 -1.17783287e+08 -1.36819272e+08 -1.54717996e+08
 -1.71846883e+08 -1.91810172e+08 -2.09621415e+08 -2.28622407e+08
 -2.48953119e+08 -2.70158646e+08]
2022.01.02:
[-7.67594731e+07 -9.58508570e+07 -1.14080843e+08 -1.34543432e+08
 -1.54531372e+08 -1.75134597e+08 -1.95878458e+08 -2.16604739e+08
 -2.37665032e+08 -2.57529916e+08]
2022.01.03:
[-5.66714304e+07 -7.21853109e+07 -9.37538168e+07 -1.14181596e+08
 -1.34082886e+08 -1.53352390e+08 -1.68023887e+08 -1.89065904e+08
 -2.09107591e+08 -2.29728417e+08]
2022.01.04:
[-3.34992412e+07 -4.90215652e+07 -6.88350436e+07 -8.85602267e+07
 -1.07932228e+08 -1.27286571e+08 -1.42155509e+08 -1.61139011e+08
 -1.80405058e+08 -2.00465764e+08]
2022.01.05:
[-1.33205382e+07 -3.13476080e+07 -5.29310385e+07 -7.14661598e+07
 -9.07195609e+07 -1.08974378e+08 -1.22989593e+08 -1.41559752e+08
 -1.59709455e+08 -1.73076466e+08]


In [81]:
print(data_ncep_olr01[:,0,2,7])

[-1.96289918e+07 -3.93648288e+07 -5.89257026e+07 -7.94838662e+07
 -9.96396146e+07 -1.17783287e+08 -1.36819272e+08 -1.54717996e+08
 -1.71846883e+08 -1.91810172e+08 -2.09621415e+08 -2.28622407e+08
 -2.48953119e+08 -2.70158646e+08 -2.91696603e+08 -3.12429729e+08
 -3.31500706e+08 -3.50011802e+08 -3.71619744e+08 -3.94085005e+08
 -4.16445288e+08 -4.37720801e+08 -4.55637021e+08 -4.72258515e+08
 -4.92309286e+08 -5.10925359e+08 -5.29611417e+08 -5.51201863e+08
 -5.71742530e+08 -5.93910354e+08 -6.17022979e+08 -6.39873159e+08
 -6.59713974e+08 -6.78505010e+08 -6.95388949e+08 -7.16332031e+08
 -7.38272403e+08 -7.59687886e+08 -7.80910909e+08 -8.01416583e+08
 -8.19875190e+08 -8.34327141e+08 -8.54482890e+08 -8.74061260e+08]


In [83]:
print(data_ncep_olr01[5,:,2,7])

[-1.17783287e+08 -1.15963671e+08 -1.15386293e+08 -1.16611035e+08
 -1.18115717e+08 -1.16506057e+08 -1.17555835e+08 -1.17083435e+08
 -1.15298811e+08 -1.11782053e+08 -1.11414631e+08 -1.11957016e+08
 -1.12359431e+08 -1.10644793e+08 -1.11029712e+08 -1.08300288e+08]


In [84]:
new_data_ncep_olr01=delete_add(data_ncep_olr01)
new_data_ncep_olr02=delete_add(data_ncep_olr02)
new_data_ncep_olr03=delete_add(data_ncep_olr03)
new_data_ncep_olr04=delete_add(data_ncep_olr04)
new_data_ncep_olr05=delete_add(data_ncep_olr05)

[-19628991.80095518 -19735836.97032034 -19560873.87661177
 -20558163.51075029 -20155748.39522076 -18143672.81757283
 -19035984.59548622 -17898724.48638093 -17128886.87406343
 -19963288.99214137]
[-20452196.16828156 -19706667.95242095 -19724247.49564344
 -16876361.49359864 -19091383.93963343 -18229986.32173103
 -20462588.31098837 -19987940.64398092 -20603224.65676832
 -20743861.00254834]
[-20747320.09662306 -19778442.73016655 -16145667.53482974
 -15513880.54433644 -21568505.8698976  -20427779.35928464
 -19901290.20054018 -19269503.21004689 -14671497.89034528
 -21042016.71115321]
[-15610601.59785151 -17888639.60557282 -15522324.00128174
 -19813478.4180184  -19725183.05964935 -19372001.62617308
 -19354342.55449927 -14868938.34935069 -18983502.04934919
 -19266047.19613022]
[-13320538.16916668 -18027069.79530919 -21583430.50322741
 -18535121.32501185 -19253401.07390171 -18254817.03276211
 -14015214.61248529 -18570159.36154306 -18149702.92316848
 -13367010.93665785]


In [85]:
print("2022.01.01:")
print(new_data_ncep_olr01[4:14,0,2,7]/86400)
print("2022.01.02:")
print(new_data_ncep_olr02[3:13,0,2,7]/86400)
print("2022.01.03:")
print(new_data_ncep_olr03[2:12,0,2,7]/86400)
print("2022.01.04:")
print(new_data_ncep_olr04[1:11,0,2,7]/86400)
print("2022.01.05:")
print(new_data_ncep_olr05[0:10,0,2,7]/86400)

2022.01.01:
[-233.28412494 -209.99621317 -220.32389578 -207.16116304 -198.25100549
 -231.05658556 -206.14864513 -219.91888862 -235.30916075 -245.43433979]
2022.01.02:
[-195.32825803 -220.96509189 -210.99521206 -236.83551286 -231.3419056
 -238.46324834 -240.09098383 -239.88751689 -243.75338866 -229.91763705]
2022.01.03:
[-186.87115202 -179.5588026  -249.63548461 -236.43263147 -230.33900695
 -223.02665752 -169.80900336 -243.54186008 -231.96397349 -238.66696046]
2022.01.04:
[-207.04443988 -179.65652779 -229.32266688 -228.30072986 -224.21298178
 -224.00859438 -172.09419386 -219.7164589  -222.98665736 -232.18409053]
2022.01.05:
[-154.17289548 -208.64664115 -249.80822342 -214.52686719 -222.84029021
 -211.28260455 -162.21313209 -214.93240002 -210.06600606 -154.71077473]


In [88]:
#检查新数据
olr_babj=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/s2s_data/babj/OLR/20060708_babj_olr.nc')
olr_ecmf=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/s2s_data/ecmf/OLR/20060708_ecmf_olr.nc')
u200_babj=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/s2s_data/babj/U200/20060708_babj_u200.nc')
u200_ecmf=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/s2s_data/ecmf/U200/20060708_ecmf_u200.nc')
u850_babj=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/s2s_data/babj/U850/20060708_babj_u850.nc')
u850_ecmf=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/s2s_data/ecmf/U850/20060708_ecmf_u850.nc')
sst_babj=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/s2s_data/babj/SST/20060708_babj_sst.nc')
sst_ecmf=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/s2s_data/ecmf/SST/20060708_ecmf_sst.nc')
time_olr_babj=np.array(olr_babj.variables['time'])
time_olr_ecmf=np.array(olr_ecmf.variables['time'])
data_olr_babj=np.array(olr_babj.variables['olr'])
data_olr_ecmf=np.array(olr_ecmf.variables['olr'])
time_sst_babj=np.array(sst_babj.variables['time'])
time_sst_ecmf=np.array(sst_ecmf.variables['time'])
data_sst_babj=np.array(sst_babj.variables['sst'])
data_sst_ecmf=np.array(sst_ecmf.variables['sst'])
time_u200_babj=np.array(u200_babj.variables['time'])
time_u200_ecmf=np.array(u200_ecmf.variables['time'])
data_u200_babj=np.array(u200_babj.variables['u200'])
data_u200_ecmf=np.array(u200_ecmf.variables['u200'])
time_u850_babj=np.array(u850_babj.variables['time'])
time_u850_ecmf=np.array(u850_ecmf.variables['time'])
data_u850_babj=np.array(u850_babj.variables['u850'])
data_u850_ecmf=np.array(u850_ecmf.variables['u850'])

In [89]:
print(data_olr_babj.shape,data_olr_ecmf.shape)
print(data_sst_babj.shape,data_sst_ecmf.shape)
print(data_u200_babj.shape,data_u200_ecmf.shape)
print(data_u850_babj.shape,data_u850_ecmf.shape)

(60, 13, 144) (46, 13, 144)
(60, 13, 144) (46, 13, 144)
(60, 13, 144) (46, 13, 144)
(60, 13, 144) (46, 13, 144)


In [91]:
start_end_time(time_olr_babj[0])
start_end_time(time_olr_ecmf[0])
start_end_time(time_sst_babj[0])
start_end_time(time_sst_ecmf[0])
start_end_time(time_u200_babj[0])
start_end_time(time_u200_ecmf[0])
start_end_time(time_u850_babj[0])
start_end_time(time_u850_ecmf[0])

start time: 2006-07-08 00:00:00
start time: 2006-07-08 00:00:00
start time: 2006-07-08 00:00:00
start time: 2006-07-08 00:00:00
start time: 2006-07-08 00:00:00
start time: 2006-07-08 00:00:00
start time: 2006-07-08 00:00:00
start time: 2006-07-08 00:00:00


In [92]:
print("re olr data:")
print(data_re_olr[20642:20652,2,7])
print("babj olr data:")
print(data_olr_babj[0:10,2,7])
print("ecmf olr data:")
print(data_olr_ecmf[0:10,2,7])

re olr data:
[-289.36526 -295.61404 -295.45477 -288.6326  -286.8275  -286.61514
 -285.2454  -273.73532 -284.85254 -284.61893]
babj olr data:
[-289.36526 -301.88928 -299.4684  -298.91876 -298.99728 -296.24915
 -298.21213 -301.11728 -302.60913 -303.70837]
ecmf olr data:
[-289.36526 -299.6382  -300.23068 -294.5254  -285.87967 -287.13043
 -287.17432 -289.17117 -287.78876 -287.50348]


In [96]:
print("re sst data:")
print(data_re_sst[20642:20652,2,132])
print("babj sst data:")
print(data_sst_babj[0:10,2,132])
print("ecmf sst data:")
print(data_sst_ecmf[0:10,2,132])

re sst data:
[300.2831  300.24646 300.21536 300.1905  300.17044 300.14694 300.12134
 300.1027  300.102   300.1262 ]
babj sst data:
[300.00012 300.00012 300.00012 300.00012 300.00012 300.00012 300.00012
 300.00012 300.00012 300.00012]
ecmf sst data:
[300.1963  300.16858 300.13342 300.09375 300.06693 300.03928 300.00677
 299.99548 299.97006 299.94684]


In [97]:
print("re u200 data:")
print(data_re_u200[20642:20652,2,7])
print("babj u200 data:")
print(data_u200_babj[0:10,2,7])
print("ecmf u200 data:")
print(data_u200_ecmf[0:10,2,7])

re u200 data:
[ 3.395613   1.8619552  4.020651   9.075934  12.568623  18.280775
 20.202187  23.35342    9.246662   3.8846471]
babj u200 data:
[ 5.2321377  1.098209   3.8347886  7.4395533  7.743316   7.1056657
 13.728107  12.772066   9.113253   3.1084116]
ecmf u200 data:
[ 3.8434324  0.5127185  6.429027  10.748287  11.111243  11.728189
 12.912628  13.455628   9.370109   5.343527 ]


In [98]:
print("re u850 data:")
print(data_re_u850[20642:20652,2,7])
print("babj u850 data:")
print(data_u850_babj[0:10,2,7])
print("ecmf u850 data:")
print(data_u850_ecmf[0:10,2,7])

re u850 data:
[ -3.480784  -14.5722275 -12.972244  -10.613211   -6.618786   -3.3989038
  -2.9563081  -3.4320984   1.9100293   1.8901125]
babj u850 data:
[-4.107511  -8.135083  -7.100681  -7.0372353 -1.862512   0.6333625
  0.6639713 -0.9037599 -2.1893284 -3.9567914]
ecmf u850 data:
[ -3.5659406  -8.899617  -10.97972    -9.030818   -4.330773   -3.3237908
  -3.1041136  -1.0671729  -1.7080041  -2.0696805]


In [99]:
#检查新加120天的数据
olr_babj=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/add_120_re_data/babj/OLR/20060708_add_120redata_babj_olr.nc')
olr_ecmf=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/add_120_re_data/ecmf/OLR/20060708_add_120redata_ecmf_olr.nc')
u200_babj=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/add_120_re_data/babj/U200/20060708_add_120redata_babj_u200.nc')
u200_ecmf=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/add_120_re_data/ecmf/U200/20060708_add_120redata_ecmf_u200.nc')
u850_babj=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/add_120_re_data/babj/U850/20060708_add_120redata_babj_u850.nc')
u850_ecmf=netCDF4.Dataset('/WdHeDisk/users/zhangnong/MJO/711_test/add_120_re_data/ecmf/U850/20060708_add_120redata_ecmf_u850.nc')
time_olr_babj=np.array(olr_babj.variables['time'])
time_olr_ecmf=np.array(olr_ecmf.variables['time'])
data_olr_babj=np.array(olr_babj.variables['olr'])
data_olr_ecmf=np.array(olr_ecmf.variables['olr'])
time_u200_babj=np.array(u200_babj.variables['time'])
time_u200_ecmf=np.array(u200_ecmf.variables['time'])
data_u200_babj=np.array(u200_babj.variables['u200'])
data_u200_ecmf=np.array(u200_ecmf.variables['u200'])
time_u850_babj=np.array(u850_babj.variables['time'])
time_u850_ecmf=np.array(u850_ecmf.variables['time'])
data_u850_babj=np.array(u850_babj.variables['u850'])
data_u850_ecmf=np.array(u850_ecmf.variables['u850'])

In [101]:
print(data_olr_babj.shape,data_olr_ecmf.shape)
print(data_u200_babj.shape,data_u200_ecmf.shape)
print(data_u850_babj.shape,data_u850_ecmf.shape)

(180, 13, 144) (166, 13, 144)
(180, 13, 144) (166, 13, 144)
(180, 13, 144) (166, 13, 144)


In [102]:
start_end_time(time_olr_babj[0])
start_end_time(time_olr_ecmf[0])
start_end_time(time_u200_babj[0])
start_end_time(time_u200_ecmf[0])
start_end_time(time_u850_babj[0])
start_end_time(time_u850_ecmf[0])

start time: 2006-03-10 00:00:00
start time: 2006-03-10 00:00:00
start time: 2006-03-10 00:00:00
start time: 2006-03-10 00:00:00
start time: 2006-03-10 00:00:00
start time: 2006-03-10 00:00:00


In [103]:
print("re olr data:")
print(data_re_olr[20522:20652,2,7])
print("babj olr data:")
print(data_olr_babj[0:130,2,7])
print("ecmf olr data:")
print(data_olr_ecmf[0:130,2,7])

re olr data:
[-198.85611 -243.48952 -219.36508 -204.70671 -224.1751  -161.19884
 -240.12888 -152.5822  -234.08183 -116.78841 -245.14064 -203.04497
 -127.39063 -241.89148 -177.05173 -217.02908 -194.52922 -174.99712
 -228.25247 -211.17848 -190.781   -211.03513 -228.4383  -149.56665
 -215.73367 -258.5195  -207.32939 -256.83655 -217.7936  -192.92056
 -179.65318 -230.07349 -146.46083 -185.44539 -133.28902 -156.75513
 -254.98367 -132.99701 -231.96883 -229.35144 -164.25156 -214.73026
 -215.31425 -213.96043 -252.88658 -201.6009  -255.92337 -264.60904
 -280.3398  -274.1866  -259.75653 -272.06827 -280.49908 -263.09064
 -233.83762 -264.72583 -273.86804 -271.25598 -272.8381  -277.14908
 -274.48392 -273.14603 -258.41333 -262.92075 -247.82704 -233.69427
 -291.00577 -283.22797 -286.26474 -287.15668 -289.47675 -289.60947
 -292.65158 -290.45892 -266.9238  -277.02164 -274.3618  -281.5025
 -267.13083 -279.36295 -291.04822 -292.3755  -288.66977 -282.69174
 -286.25412 -289.82715 -297.2333  -294.15933 -292.

In [104]:
print("re u200 data:")
print(data_re_u200[20522:20652,2,7])
print("babj u200 data:")
print(data_u200_babj[0:130,2,7])
print("ecmf u200 data:")
print(data_u200_ecmf[0:130,2,7])

re u200 data:
[-16.510107   -17.893293   -14.580014   -13.098443   -14.38903
 -16.492746    -5.6211376   -6.1217465  -12.652814    -9.423451
  -4.747242    -3.1962218   -6.1506834  -13.587477    -4.3913174
  -7.0969214   -9.987721    -5.4504094   -7.5338693   -8.783945
 -14.386136    -6.1217465   -8.914161   -10.907916    -8.228355
  -7.2473936   -8.532193    -7.5367627    2.46095      5.7047806
   3.592384     5.4501357    5.991256     2.3509893   -4.8514147
  -5.8005466   -9.180381   -11.828111    -4.874564    -2.5653965
  -0.9304595   -3.630276     3.3840382    1.9719155   -0.1260126
   2.2265606   10.927898    17.27377      7.915563     5.0855303
  11.960947    14.880684     8.161527     1.6217786    5.2996635
   3.4245498    8.5984745    9.373984     9.290068     6.9259195
   9.266918    10.508313     8.433534     1.636247     1.7982938
   8.450896    17.910381    13.833167    12.180868     9.49552
   8.578218    13.621927    10.531463     4.2521462    6.8796206
   4.2058473   -1.

In [105]:
print("re u850 data:")
print(data_re_u850[20522:20652,2,7])
print("babj u850 data:")
print(data_u850_babj[0:130,2,7])
print("ecmf u850 data:")
print(data_u850_ecmf[0:130,2,7])

re u850 data:
[  2.1269011    2.7376828    8.827797     4.0521917    2.0892806
   1.2284323   -2.5424814    2.7421088   -1.497956     1.3258033
  -0.19893824  -0.02190003   6.0217414   -0.9823323    3.5631235
   0.62871534   1.1664689    1.8392141    6.085918     8.478147
   2.7443218   -1.1306018   -2.195044    -1.5842621   -3.6002846
  -2.3344615   -3.0912998   -5.2312493   -3.469719    -3.6268404
  -0.7278399   -2.7637792   -2.77927     -1.9051439    3.897283
   0.5888818   -3.7286375    2.0981324   -3.8835459   -1.305427
  -2.5557592   -5.414926    -2.6221485    4.408481     2.4190142
  -1.5178728   -3.6910167   -7.3335776  -11.5493     -10.24143
 -12.051646    -9.958169    -5.051998    -1.8741622   -1.2921492
  -1.0000361   -2.867789     0.21267559  -4.3991694   -9.0397835
 -11.339067    -7.1764565   -2.887706     0.02235952   0.53134435
  -0.19008632   5.176384     5.703073     5.875685     4.1030903
   2.0051873    4.7559185    5.3423576    4.629779   -10.965074
  -9.130515    -

In [106]:
#导入模式数据气候态
season_babj_olr=np.load('/WdHeDisk/users/zhangnong/MJO/711_test/seasonal_cycle/babj/OLR/0708_seasonal_cycle_olr.npy')
season_babj_u200=np.load('/WdHeDisk/users/zhangnong/MJO/711_test/seasonal_cycle/babj/U200/0708_seasonal_cycle_u200.npy')
season_babj_u850=np.load('/WdHeDisk/users/zhangnong/MJO/711_test/seasonal_cycle/babj/U850/0708_seasonal_cycle_u850.npy')
print(season_babj_olr.shape,season_babj_u200.shape,season_babj_u850.shape)
season_ecmf_olr=np.load('/WdHeDisk/users/zhangnong/MJO/711_test/seasonal_cycle/ecmf/OLR/0708_seasonal_cycle_olr.npy')
season_ecmf_u200=np.load('/WdHeDisk/users/zhangnong/MJO/711_test/seasonal_cycle/ecmf/U200/0708_seasonal_cycle_u200.npy')
season_ecmf_u850=np.load('/WdHeDisk/users/zhangnong/MJO/711_test/seasonal_cycle/ecmf/U850/0708_seasonal_cycle_u850.npy')
print(season_ecmf_olr.shape,season_ecmf_u200.shape,season_ecmf_u850.shape)

(180, 13, 144) (180, 13, 144) (180, 13, 144)
(166, 13, 144) (166, 13, 144) (166, 13, 144)


In [110]:
print("re olr data:")
print(data_re_olr[20642:20652,2,7]-season_re_olr[20642:20652,2,7])
print("babj olr data:")
print(data_olr_babj[120:130,2,7]-season_babj_olr[120:130,2,7])
print("ecmf olr data:")
print(data_olr_ecmf[120:130,2,7]-season_ecmf_olr[120:130,2,7])

re olr data:
[ -6.094635  -13.852264  -12.403229   -6.1089783  -7.0711365  -3.8971863
  -2.7994995   8.481262   -3.1105652  -6.8563232]
babj olr data:
[ -4.8023987  -11.975433    -9.2864685   -4.1307983   -4.974457
  -0.33096313   0.6948242   -2.880066    -3.0625916   -4.36084   ]
ecmf olr data:
[ -5.157898   -11.180664   -10.174469    -5.449585     0.9384155
  -0.9578552    0.25775146  -1.8569336   -1.5760193   -0.67266846]


In [111]:
print("re u200 data:")
print(data_re_u200[20642:20652,2,7]-season_re_u200[20642:20652,2,7])
print("babj u200 data:")
print(data_u200_babj[120:130,2,7]-season_babj_u200[120:130,2,7])
print("ecmf u200 data:")
print(data_u200_ecmf[120:130,2,7]-season_ecmf_u200[120:130,2,7])

re u200 data:
[-2.5324643 -3.2169194 -0.8530612  4.5988517  7.6121507 13.219841
 15.819439  19.674322   7.0954337  1.7104626]
babj u200 data:
[ 1.5486584  -2.2073927   0.45654798  4.9426503   5.2567363   2.8793168
  8.522228    7.9149666   4.4509816  -1.7797396 ]
ecmf u200 data:
[-1.9961181 -5.4389515  1.8857388  6.850041   6.6956615  7.082819
  7.6452265  8.838227   6.463413   3.375732 ]


In [112]:
print("re u850 data:")
print(data_re_u850[20642:20652,2,7]-season_re_u850[20642:20652,2,7])
print("babj u850 data:")
print(data_u850_babj[120:130,2,7]-season_babj_u850[120:130,2,7])
print("ecmf u850 data:")
print(data_u850_ecmf[120:130,2,7]-season_ecmf_u850[120:130,2,7])

re u850 data:
[ 4.23409   -6.164027  -5.268656  -4.447347  -1.1863761  2.0215545
  1.8560984  1.5162582  7.2804747  6.8146434]
babj u850 data:
[ 1.9042835  -1.5956779  -2.0104065  -3.0429587   1.1342741   3.248774
  2.0432193   0.45875245  0.67607427 -0.8750019 ]
ecmf u850 data:
[ 3.760184   -0.69874763 -3.9491858  -3.6077604   0.45100164  0.9785936
  0.6998732   2.4019198   2.4776096   2.4300168 ]


In [ ]:
#eof1,eof2: [51.37508737 48.82820937]


In [113]:
re_rmm=np.loadtxt('/WdHeDisk/users/zhangnong/MJO/711_test/pca_RMM_1950_2022.txt')
re_babj_rmm=np.load('/WdHeDisk/users/zhangnong/MJO/711_test/re_RMM/babj/20060708_babj_rmm.npy')
re_ecmf_rmm=np.load('/WdHeDisk/users/zhangnong/MJO/711_test/re_RMM/ecmf/20060708_ecmf_rmm.npy')
print(re_rmm.shape,re_babj_rmm.shape,re_ecmf_rmm.shape)

(26209, 3) (60, 2) (46, 2)


In [116]:
#输出同一段时间，看看是否找错了
print("re rmm:")
print(re_rmm[20522:20582,:])


re rmm:
[[ 2.00607080e+07  1.04919757e+00 -1.08700875e+00]
 [ 2.00607090e+07  8.63163320e-01 -9.12377270e-01]
 [ 2.00607100e+07  6.48196390e-01 -7.51264080e-01]
 [ 2.00607110e+07  5.75186450e-01 -8.28705030e-01]
 [ 2.00607120e+07  6.44627220e-01 -1.00065094e+00]
 [ 2.00607130e+07  5.49255240e-01 -1.23455276e+00]
 [ 2.00607140e+07  3.94763710e-01 -9.86536520e-01]
 [ 2.00607150e+07  5.35856110e-01 -1.01853420e+00]
 [ 2.00607160e+07  6.96950800e-01 -8.16153910e-01]
 [ 2.00607170e+07  7.07130830e-01 -9.73550570e-01]
 [ 2.00607180e+07  5.16112480e-01 -1.12588009e+00]
 [ 2.00607190e+07  2.65988100e-01 -9.89589890e-01]
 [ 2.00607200e+07  1.39466090e-01 -9.97872130e-01]
 [ 2.00607210e+07  8.02925300e-02 -1.09260298e+00]
 [ 2.00607220e+07  2.11990980e-01 -1.09650321e+00]
 [ 2.00607230e+07  2.55718500e-01 -1.03539681e+00]
 [ 2.00607240e+07  1.76217580e-01 -1.02928637e+00]
 [ 2.00607250e+07 -3.48740030e-01 -8.75514430e-01]
 [ 2.00607260e+07 -8.55192620e-01 -7.92684720e-01]
 [ 2.00607270e+07 -7.39

In [117]:
print("ecmf rmm")
print(re_ecmf_rmm)

ecmf rmm
[[ 1.04919757 -1.08700875]
 [ 0.86316332 -0.91237727]
 [ 0.64819639 -0.75126408]
 [ 0.57518645 -0.82870503]
 [ 0.64462722 -1.00065094]
 [ 0.54925524 -1.23455276]
 [ 0.39476371 -0.98653652]
 [ 0.53585611 -1.0185342 ]
 [ 0.6969508  -0.81615391]
 [ 0.70713083 -0.97355057]
 [ 0.51611248 -1.12588009]
 [ 0.2659881  -0.98958989]
 [ 0.13946609 -0.99787213]
 [ 0.08029253 -1.09260298]
 [ 0.21199098 -1.09650321]
 [ 0.2557185  -1.03539681]
 [ 0.17621758 -1.02928637]
 [-0.34874003 -0.87551443]
 [-0.85519262 -0.79268472]
 [-0.73923361 -0.66862847]
 [-0.44510039 -0.42372187]
 [-0.5962683  -0.11010867]
 [-0.85564803  0.0413258 ]
 [-1.04323925  0.05957484]
 [-0.98345203  0.05814936]
 [-0.81429162  0.28987349]
 [-0.7016151   0.42959483]
 [-0.60321345  0.14435616]
 [-0.17756102  0.15496073]
 [ 0.13893017  0.24496503]
 [ 0.70875405  0.32661214]
 [ 0.859315    0.44175055]
 [ 0.66622845  0.5279587 ]
 [ 0.81449972  0.63805426]
 [ 0.98012642  0.56287129]
 [ 0.76258669  0.28302018]
 [ 0.8866754   0.07

In [118]:
print("babj rmm:")
print(re_babj_rmm)

babj rmm:
[[ 1.04919757 -1.08700875]
 [ 0.86316332 -0.91237727]
 [ 0.64819639 -0.75126408]
 [ 0.57518645 -0.82870503]
 [ 0.64462722 -1.00065094]
 [ 0.54925524 -1.23455276]
 [ 0.39476371 -0.98653652]
 [ 0.53585611 -1.0185342 ]
 [ 0.6969508  -0.81615391]
 [ 0.70713083 -0.97355057]
 [ 0.51611248 -1.12588009]
 [ 0.2659881  -0.98958989]
 [ 0.13946609 -0.99787213]
 [ 0.08029253 -1.09260298]
 [ 0.21199098 -1.09650321]
 [ 0.2557185  -1.03539681]
 [ 0.17621758 -1.02928637]
 [-0.34874003 -0.87551443]
 [-0.85519262 -0.79268472]
 [-0.73923361 -0.66862847]
 [-0.44510039 -0.42372187]
 [-0.5962683  -0.11010867]
 [-0.85564803  0.0413258 ]
 [-1.04323925  0.05957484]
 [-0.98345203  0.05814936]
 [-0.81429162  0.28987349]
 [-0.7016151   0.42959483]
 [-0.60321345  0.14435616]
 [-0.17756102  0.15496073]
 [ 0.13893017  0.24496503]
 [ 0.70875405  0.32661214]
 [ 0.859315    0.44175055]
 [ 0.66622845  0.5279587 ]
 [ 0.81449972  0.63805426]
 [ 0.98012642  0.56287129]
 [ 0.76258669  0.28302018]
 [ 0.8866754   0.0

In [119]:
babj_rmm=np.load('/WdHeDisk/users/zhangnong/MJO/711_test/s2s_RMM/babj/20060708_babj_rmm.npy')
ecmf_rmm=np.load('/WdHeDisk/users/zhangnong/MJO/711_test/s2s_RMM/ecmf/20060708_ecmf_rmm.npy')
print(babj_rmm.shape,ecmf_rmm.shape)

(60, 2) (46, 2)


In [120]:
print(babj_rmm)

[[ 1.1477882  -1.00240421]
 [ 0.78778327 -1.10976865]
 [ 0.41574477 -0.74160617]
 [ 0.44620477 -0.47046012]
 [ 0.66399997 -0.53116109]
 [ 0.68867596 -0.56762183]
 [ 0.55129135 -0.46635954]
 [ 0.44902576 -0.43267563]
 [ 0.57887044 -0.58071675]
 [ 0.48391163 -0.42894069]
 [ 0.37554953 -0.0939134 ]
 [ 0.16620859  0.16830096]
 [-0.12063549  0.23992281]
 [-0.03129438  0.03261911]
 [ 0.03929616 -0.10189554]
 [-0.05771413 -0.3986192 ]
 [-0.14708943 -0.69310568]
 [-0.22741147 -0.96019195]
 [-0.27401637 -1.22575709]
 [-0.37594487 -1.40720714]
 [-0.34249732 -1.39084914]
 [-0.31296577 -1.17416017]
 [-0.33481482 -0.86061676]
 [-0.24211709 -0.56097133]
 [-0.19044404 -0.30484435]
 [-0.15040863 -0.28035387]
 [-0.13615521 -0.26407565]
 [-0.19337112 -0.08110687]
 [-0.30114288  0.14400684]
 [-0.31545265  0.26119733]
 [-0.43338497  0.31746902]
 [-0.54202636  0.45852946]
 [-0.53067152  0.49609779]
 [-0.47909843  0.4797052 ]
 [-0.52841041  0.62382565]
 [-0.6203738   0.65868417]
 [-0.62220612  0.59623085]
 

In [121]:
print(ecmf_rmm)

[[ 1.10568406 -0.77399658]
 [ 0.97030532 -0.63326864]
 [ 0.81434338 -0.43262542]
 [ 0.73747911 -0.50876572]
 [ 0.74727475 -0.81866974]
 [ 0.72943085 -0.88371774]
 [ 0.57713962 -0.78087141]
 [ 0.59347532 -0.83013301]
 [ 0.7431787  -0.82951026]
 [ 0.70589102 -0.75498932]
 [ 0.5767524  -0.6700018 ]
 [ 0.33553712 -0.66805101]
 [ 0.14451865 -0.70884002]
 [ 0.13748713 -0.72655854]
 [ 0.12435744 -0.73327322]
 [ 0.14644491 -0.78571339]
 [ 0.16733896 -0.87654605]
 [ 0.11757021 -0.8249223 ]
 [ 0.11909463 -0.73495935]
 [ 0.11373354 -0.6429771 ]
 [-0.00653059 -0.55374218]
 [-0.07910741 -0.5773566 ]
 [-0.1483202  -0.59008826]
 [-0.22640048 -0.45340878]
 [-0.40087148 -0.30378509]
 [-0.54273357 -0.18085181]
 [-0.57097742 -0.07443433]
 [-0.58816708  0.04602936]
 [-0.59149374  0.15473265]
 [-0.51119645  0.27194473]
 [-0.45548477  0.31460828]
 [-0.33056855  0.29720173]
 [-0.32290487  0.26573775]
 [-0.29371499  0.29942687]
 [-0.22900041  0.32375799]
 [-0.16652488  0.29411623]
 [-0.07623471  0.21944955]
 